default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

cloud9:
  <<: *default
  database: ajaxhealth_development
  username: ubuntu
  password: password

test:
  <<: *default
  database: ajaxhealth_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  
development:
  <<: *default
  host: localhost
  database: ajaxhealth_development